create table public.confirma_packages (code text primary key,label text not null,credits integer not null check(credits>0),price_cents integer not null check(price_cents>0),description text not null,recommended boolean not null default false,active boolean not null default true,sort_order smallint not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
insert into public.confirma_packages(code,label,credits,price_cents,description,recommended,sort_order) values ('PACKAGE_5','5 confirmações',5,990,'Ideal para experimentar.',false,10),('PACKAGE_20','20 confirmações',20,2490,'Melhor custo para quem usa com frequência.',true,20),('PACKAGE_50','50 confirmações',50,4990,'Menor custo por confirmação.',false,30);
create table public.confirma_wallets(id uuid primary key default gen_random_uuid(),access_token_hash text not null unique check(char_length(access_token_hash)=64),balance integer not null default 0 check(balance>=0),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),last_seen_at timestamptz not null default now());
create table public.confirma_orders(id uuid primary key default gen_random_uuid(),wallet_id uuid not null references public.confirma_wallets(id),package_code text not null references public.confirma_packages(code),expected_price_cents integer not null check(expected_price_cents>0),expected_credits integer not null check(expected_credits>0),provider text not null default 'mercadopago' check(provider='mercadopago'),status text not null default 'created' check(status in('created','pending','approved','rejected','cancelled')),provider_preference_id text unique,provider_payment_id text unique,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),approved_at timestamptz);
create index confirma_orders_wallet_created_idx on public.confirma_orders(wallet_id,created_at desc);create index confirma_orders_status_created_idx on public.confirma_orders(status,created_at desc);create index confirma_orders_package_code_idx on public.confirma_orders(package_code);
create table public.confirma_confirmations(id uuid primary key default gen_random_uuid(),wallet_id uuid not null references public.confirma_wallets(id),client_confirmation_id text not null check(char_length(client_confirmation_id) between 8 and 120),payload jsonb not null,finalized_at timestamptz not null default now(),unique(wallet_id,client_confirmation_id));
create index confirma_confirmations_wallet_finalized_idx on public.confirma_confirmations(wallet_id,finalized_at desc);
create table public.confirma_credit_ledger(id bigint generated always as identity primary key,wallet_id uuid not null references public.confirma_wallets(id),delta integer not null check(delta<>0),reason text not null check(reason in('purchase','confirmation')),source_type text not null check(source_type in('payment','confirmation')),source_id text not null,balance_after integer not null check(balance_after>=0),metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),unique(source_type,source_id));
create index confirma_credit_ledger_wallet_created_idx on public.confirma_credit_ledger(wallet_id,created_at desc);
create table public.confirma_events(id bigint generated always as identity primary key,wallet_id uuid references public.confirma_wallets(id) on delete set null,event_name text not null check(char_length(event_name) between 1 and 80),properties jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create index confirma_events_name_created_idx on public.confirma_events(event_name,created_at desc);create index confirma_events_wallet_created_idx on public.confirma_events(wallet_id,created_at desc) where wallet_id is not null;
alter table public.confirma_packages enable row level security;alter table public.confirma_wallets enable row level security;alter table public.confirma_orders enable row level security;alter table public.confirma_confirmations enable row level security;alter table public.confirma_credit_ledger enable row level security;alter table public.confirma_events enable row level security;
revoke all on table public.confirma_packages,public.confirma_wallets,public.confirma_orders,public.confirma_confirmations,public.confirma_credit_ledger,public.confirma_events from anon,authenticated;
grant select,insert,update,delete on table public.confirma_packages,public.confirma_wallets,public.confirma_orders,public.confirma_confirmations,public.confirma_credit_ledger,public.confirma_events to service_role;grant usage,select on all sequences in schema public to service_role;

create or replace function public.confirma_apply_approved_payment(p_order_id uuid,p_provider_payment_id text,p_amount_cents integer) returns table(balance integer,credits_added integer,applied boolean) language plpgsql security definer set search_path=public,pg_temp as $$ declare v_order public.confirma_orders%rowtype;v_balance integer;begin select * into v_order from public.confirma_orders where id=p_order_id for update;if not found then raise exception 'ORDER_NOT_FOUND';end if;if v_order.status='approved' then if v_order.provider_payment_id is distinct from p_provider_payment_id then raise exception 'ORDER_ALREADY_APPROVED_WITH_DIFFERENT_PAYMENT';end if;select w.balance into v_balance from public.confirma_wallets w where w.id=v_order.wallet_id;return query select v_balance,v_order.expected_credits,false;return;end if;if p_amount_cents is distinct from v_order.expected_price_cents then raise exception 'PAYMENT_AMOUNT_MISMATCH';end if;if exists(select 1 from public.confirma_orders o where o.provider_payment_id=p_provider_payment_id and o.id<>p_order_id) then raise exception 'PAYMENT_ALREADY_LINKED_TO_ANOTHER_ORDER';end if;update public.confirma_wallets w set balance=w.balance+v_order.expected_credits,updated_at=now(),last_seen_at=now() where w.id=v_order.wallet_id returning w.balance into v_balance;insert into public.confirma_credit_ledger(wallet_id,delta,reason,source_type,source_id,balance_after,metadata) values(v_order.wallet_id,v_order.expected_credits,'purchase','payment',p_provider_payment_id,v_balance,jsonb_build_object('order_id',p_order_id,'package_code',v_order.package_code,'amount_cents',p_amount_cents));update public.confirma_orders o set status='approved',provider_payment_id=p_provider_payment_id,approved_at=now(),updated_at=now() where o.id=p_order_id;return query select v_balance,v_order.expected_credits,true;end;$$;

create or replace function public.confirma_finalize_confirmation(p_wallet_id uuid,p_client_confirmation_id text,p_payload jsonb) returns table(confirmation_id uuid,balance integer,consumed boolean) language plpgsql security definer set search_path=public,pg_temp as $$ declare v_existing_id uuid;v_confirmation_id uuid;v_balance integer;begin select c.id into v_existing_id from public.confirma_confirmations c where c.wallet_id=p_wallet_id and c.client_confirmation_id=p_client_confirmation_id;if found then select w.balance into v_balance from public.confirma_wallets w where w.id=p_wallet_id;return query select v_existing_id,v_balance,false;return;end if;select w.balance into v_balance from public.confirma_wallets w where w.id=p_wallet_id for update;if not found then raise exception 'WALLET_NOT_FOUND';end if;select c.id into v_existing_id from public.confirma_confirmations c where c.wallet_id=p_wallet_id and c.client_confirmation_id=p_client_confirmation_id;if found then return query select v_existing_id,v_balance,false;return;end if;if v_balance<=0 then raise exception 'INSUFFICIENT_CREDITS';end if;insert into public.confirma_confirmations(wallet_id,client_confirmation_id,payload) values(p_wallet_id,p_client_confirmation_id,p_payload) returning id into v_confirmation_id;update public.confirma_wallets w set balance=w.balance-1,updated_at=now(),last_seen_at=now() where w.id=p_wallet_id returning w.balance into v_balance;insert into public.confirma_credit_ledger(wallet_id,delta,reason,source_type,source_id,balance_after,metadata) values(p_wallet_id,-1,'confirmation','confirmation',v_confirmation_id::text,v_balance,jsonb_build_object('client_confirmation_id',p_client_confirmation_id));return query select v_confirmation_id,v_balance,true;end;$$;
revoke all on function public.confirma_apply_approved_payment(uuid,text,integer),public.confirma_finalize_confirmation(uuid,text,jsonb) from public,anon,authenticated;grant execute on function public.confirma_apply_approved_payment(uuid,text,integer),public.confirma_finalize_confirmation(uuid,text,jsonb) to service_role;